### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mikeymike** [mikeymike/php-workshop#1]
- [ ] Initial console menu (with Climate ?)
- [x] Lesson / Task interface
- [x] Lesson / Task validators (default being a simple expects)
- [ ] Lesson / Task page, output details
- [x] Lesson / Task runner
- [ ] All the tests
- [ ] Move SyntaxHighlighter to separate package
- [ ] Finish tests for SyntaxHighlighter
- [ ] Docs for SyntaxHighlighter 
- [ ] Pin php-workshop to php-parser 2.x@beta
- [ ] Fix tests (Update usages of php-parser to 2.x)
- [ ] Add CLI command parsing (verify, run, help) etc
- [ ] Fix mark-down URLS's (don't wrap in curly braces)
- [ ] Build output page for task
- [ ] Replace variables in markdown files, like `{appname}`
- [ ] Use Terminal object in markdown-render for stuff like screen width

![Welcome!](http://www.reactiongifs.com/r/wtfs.gif)
